version: "3.8"

services:
  backend:
    build:
      context: backend
    restart: on-failure:3
    environment:
      - APP_NAME=Diapp
    volumes:
      - 'record:/app/records'
    ports:
      - '5000:5000'

  frontend:
    build:
      context: frontend
    restart: on-failure:3
    ports:
      - '8080:80'

volumes:
  record:
    driver: local
    driver_opts:
      type: none
      device: './recordings'
      o: bind
